apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: hpc-sentinel
build:
  local:
    push: false 
    useBuildkit: true
  tagPolicy:
    sha256: {} 
  artifacts:
    - image: scenario-manager
      context: .
      docker:
        dockerfile: build/scenario-manager/Dockerfile
    - image: dcgm-mock-exporter
      context: .
      docker:
        dockerfile: build/dcgm-mock-exporter/Dockerfile
    - image: kube-hpc-sentinel
      context: .
      docker:
        dockerfile: build/manager/Dockerfile
    - image: fake-hpc-job
      context: .
      docker:
        dockerfile: build/fake-hpc-job/Dockerfile
manifests:
  rawYaml:
    - internal/provisioner/manifests/scenario-manager.yaml
    - internal/provisioner/manifests/dcgm-mock-exporter.yaml
    - internal/provisioner/manifests/grafana-dashboard.yaml
    - deploy/kube-hpc-sentinel.yaml
    # - deploy/example-hpc-job.yaml
deploy:
  kubectl: {}

