apiVersion: hpc.nvidia.com/v1alpha1
kind: HPCJob
metadata:
  name: gpu-burn-test
  namespace: default
spec:
  image: fake-hpc-job

  # Minimum GPUs required on a single node
  gpuCount: 2

  # Hardware placement requirements
  # constraints:
  #   topology: "nvlink"
