apiVersion: hpc.nvidia.com/v1alpha1
kind: HPCJob
metadata:
  name: test-inference-task
  namespace: default
spec:
  image: fake-hpc-job

  # Minimum GPUs required on a single node
  gpuCount: 4

  # Hardware placement requirements
  # constraints:
  #   topology: "nvlink"
