apiVersion: hpc.nvidia.com/v1alpha1
kind: HPCJob
metadata:
  labels:
    app.kubernetes.io/name: kube-hpc-sentinel
    app.kubernetes.io/managed-by: kustomize
  name: hpcjob-sample
spec:
  image: nvidia/cuda:12.0-runtime
  gpuCount: 4
  constraints:
    topology: nvlink
